<ul class="form-list" id="payment_form_crvlegalpayment" style="display:none;">
  <!--  <li>
        <label for="legal_company"><?php echo Mage::helper("crvlegalpayment")->__("Company name") ?></label>
        <div class="input-box">
            <input id="legal_company" type="text" name="payment[legal_company]" title="<?php echo Mage::helper("crvlegalpayment")->__("Company name") ?>" />
        </div>
    </li> -->
    <li>
        <label for="legal_tax"><?php echo Mage::helper("crvlegalpayment")->__("Individual Taxpayer Number") ?></label>
        <div class="input-box">
            <input id="legal_tax" type="text" name="payment[legal_tax]" title="<?php echo Mage::helper("crvlegalpayment")->__("Individual Taxpayer Number") ?>" />
        </div>
    </li>
    <li>
        <label for="legal_classifier"><?php echo Mage::helper("crvlegalpayment")->__("Industrial Enterprises Classifier") ?></label>
        <div class="input-box">
            <input id="legal_tax" type="text" name="payment[legal_classifier]" title="<?php echo Mage::helper("crvlegalpayment")->__("Industrial Enterprises Classifier") ?>" />
        </div>
    </li>
    <li>
        <label for="legal_bankname"><?php echo Mage::helper("crvlegalpayment")->__("Bank name") ?></label>
        <div class="input-box">
            <input id="legal_bankname" type="text" name="payment[legal_bankname]" title="<?php echo Mage::helper("crvlegalpayment")->__("Bank name") ?>" />
        </div>
    </li>
    <li>
        <label for="legal_banknumber"><?php echo Mage::helper("crvlegalpayment")->__("Bank Identification Code") ?></label>
        <div class="input-box">
            <input id="legal_banknumber" type="text" name="payment[legal_banknumber]" title="<?php echo Mage::helper("crvlegalpayment")->__("Bank Identification Code") ?>" />
        </div>
    </li>
    <li>
        <label for="legal_bankaccount"><?php echo Mage::helper("crvlegalpayment")->__("Current (checking) account") ?></label>
        <div class="input-box">
            <input id="legal_bankaccount" type="text" name="payment[legal_bankaccount]" title="<?php echo Mage::helper("crvlegalpayment")->__("Current (checking) account") ?>" />
        </div>
    </li>
    <li>
        <label for="legal_bankсorresponding"><?php echo Mage::helper("crvlegalpayment")->__("Correspondent account") ?></label>
        <div class="input-box">
            <input id="legal_bankсorresponding" type="text" name="payment[legal_bankсorresponding]" title="<?php echo Mage::helper("crvlegalpayment")->__("orrespondent account") ?>" />
        </div>
    </li>
</ul>